name: Build & Deploy - staging
concurrency:
  group: deploy-staging
  cancel-in-progress: false
on:
  workflow_dispatch:
  pull_request:
    branches: [ development ]
    types:
      - opened
      - synchronize
env:
  AWS_REGION: us-west-2
jobs:
  bitrise-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.head_ref }}
