name: Webhook Trigger
concurrency:
  group: webhook-trigger
  cancel-in-progress: false
on:
  repository_dispatch:
    types:
      - webhook

jobs:
  webhook-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log info
        run: |
          echo "Run successful !!"
